export type Brand = {
  slug: string;
  name: string;
  country: string;
  type: string;
  since: string;
  image: string;
  logo?: string;
  logoText: string;
  short: string;
  intro: string;
  story: string;
  accent: string;
};

export type Product = {
  id: string;
  brand: string;
  name: string;
  country: string;
  type: string;
  volume: string;
  abv?: string;
  pack?: string;
  composition?: string;
  shelfLife?: string;
  image: string;
  description: string;
};

export const publicBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export function assetPath(path: string) {
  return `${publicBasePath}${path}`;
}

export const brands: Brand[] = [
  {
    slug: "tsingtao",
    name: "Tsingtao",
    country: "Китай",
    type: "Китайское пиво",
    since: "с 1903 года",
    image: assetPath("/products/tsingtao-range.webp"),
    logo: assetPath("/brands/tsingtao.png"),
    logoText: "TSINGTAO",
    short: "Один из самых известных китайских пивных брендов с более чем вековой историей.",
    intro: "Пивоварня Tsingtao известна во всём мире, а её продукция представлена более чем в 100 странах.",
    story: "Лёгкие освежающие лагеры Tsingtao подходят к самой разной кухне. В производстве используются родниковая вода из высокогорного региона Laoshan, дрожжи, злаковые и местный рис. В коллекции также представлены пшеничное пиво, IPA, стаут и безалкогольная версия.",
    accent: "#b85032",
  },
  {
    slug: "harbin",
    name: "Harbin",
    country: "Китай",
    type: "Китайское пиво",
    since: "с 1900 года",
    image: assetPath("/products/harbin-range.webp"),
    logo: assetPath("/brands/harbin.png"),
    logoText: "HARBIN",
    short: "Светлый китайский лагер с гладким, сбалансированным вкусом.",
    intro: "Harbin Premium — лагер бледно-золотистого цвета с нотами солода, зерна и трав.",
    story: "В коллекции Status Groupp Harbin Premium представлен в двух бутылочных форматах: 0,33 и 0,61 л. Обе позиции имеют крепость 5,5% и подходят для ритейла и заведений азиатской кухни.",
    accent: "#507f99",
  },
  {
    slug: "yanjing",
    name: "Yanjing Beer",
    country: "Китай",
    type: "Пекинский лагер",
    since: "Пекин",
    image: assetPath("/products/imported/yanjing-lager.png"),
    logo: assetPath("/brands/yanjing.png"),
    logoText: "YANJING BEER",
    short: "Эталонный азиатский лагер с мягким вкусом и безалкогольной версией.",
    intro: "Yanjing Beer представляет классический пекинский лагер, особенно подходящий к паназиатским блюдам.",
    story: "Линейка включает лагер в форматах 0,33 и 0,61 л, а также безалкогольную версию 0,33 л. Мягкий вкус хорошо подчёркивает остроту азиатской кухни.",
    accent: "#d5a312",
  },
  {
    slug: "ha-noi",
    name: "Bia Hà Nội",
    country: "Вьетнам",
    type: "Вьетнамский лагер",
    since: "Ханой",
    image: assetPath("/products/imported/ha-noi.jpg"),
    logo: assetPath("/brands/ha-noi.png"),
    logoText: "BIA HÀ NỘI",
    short: "Светлый лагер из Ханоя с гармоничными солодово-хмелевыми оттенками.",
    intro: "Bia Hà Nội — освежающий вьетнамский лагер на основе солода, риса и хмеля.",
    story: "Пиво демонстрирует приятный, гармоничный вкус и аромат с характерными солодово-хмелевыми оттенками. В ассортименте представлены банки 0,33 и 0,49 л.",
    accent: "#c3442f",
  },
  {
    slug: "kaisar-king",
    name: "Kaisar King",
    country: "Китай",
    type: "Фруктовое пшеничное",
    since: "яркая линейка 1 л",
    image: assetPath("/products/imported/kaisar-passionfruit.jpeg"),
    logoText: "KAISAR KING",
    short: "Пшеничные напитки с маракуйей, клубникой и персиком в литровом формате.",
    intro: "Kaisar King соединяет мягкую пшеничную основу с яркими фруктовыми вкусами.",
    story: "В коллекции представлены три варианта крепостью 4,5%: маракуйя, клубника и персик. Все позиции выпускаются в стальной банке объёмом 1 л.",
    accent: "#d5a500",
  },
  {
    slug: "tok-rene",
    name: "TOK RENE",
    country: "Китай",
    type: "Пшеничные и крафтовые",
    since: "форматы 1 и 5 л",
    image: assetPath("/products/imported/tok-rene-belgian-wheat.jpeg"),
    logoText: "TOK RENE",
    short: "Фруктовые пшеничные напитки и большие пятилитровые форматы.",
    intro: "TOK RENE — линейка для заметной выкладки: от фруктовых напитков 1 л до кегов 5 л.",
    story: "Ассортимент включает вишнёвый и ананасово-кокосовый варианты крепостью 4,3%, а также Belgian Wheat и Craft White крепостью 5,0% в формате 5 л.",
    accent: "#bf7436",
  },
  {
    slug: "big-bisar",
    name: "Big Bisar",
    country: "Китай",
    type: "Светлое пиво",
    since: "банка 0,5 л",
    image: assetPath("/products/imported/big-bisar.jpeg"),
    logoText: "BIG BISAR",
    short: "Лёгкое фильтрованное пиво крепостью 3,3% в алюминиевой банке.",
    intro: "Big Bisar — светлое пастеризованное пиво в удобном розничном формате 0,5 л.",
    story: "Позиция имеет крепость 3,3%, плотность 10° и поставляется по 12 банок в упаковке.",
    accent: "#2d6280",
  },
  {
    slug: "berlin-priest",
    name: "Berlin Priest",
    country: "Китай",
    type: "Пиво в больших форматах",
    since: "банка 2 л",
    image: assetPath("/products/imported/berlin-priest-stout.jpg"),
    logoText: "BERLIN PRIEST",
    short: "Стаут и пшеничное белое пиво в двухлитровой стальной банке.",
    intro: "Berlin Priest предлагает два выразительных стиля в большом формате для компании.",
    story: "В линейке представлены тёмный Stout и светлое нефильтрованное White Beer. Обе позиции имеют крепость 5,0% и поставляются по 6 банок в упаковке.",
    accent: "#805332",
  },
  {
    slug: "singha",
    name: "Singha",
    country: "Таиланд",
    type: "Тайское пиво",
    since: "с 1933 года",
    image: assetPath("/products/singha-range.webp"),
    logoText: "SINGHA",
    short: "Ярко-золотой тайский лагер с узнаваемым львом на этикетке.",
    intro: "Singha производится Boon Rawd Brewery с 1933 года и известен далеко за пределами Таиланда.",
    story: "Премиальный лагер обладает дрожжевым оттенком и лёгкой горчинкой. Его вкус особенно хорошо раскрывается рядом с пряной тайской кухней.",
    accent: "#c69a2b",
  },
  {
    slug: "leo",
    name: "Leo",
    country: "Таиланд",
    type: "Тайский лагер",
    since: "популярный бренд Таиланда",
    image: assetPath("/products/leo-050.webp"),
    logoText: "LEO",
    short: "Сбалансированный светлый лагер с ровным и чистым характером.",
    intro: "Leo — популярный тайский лагер для повседневных гастрономических сочетаний.",
    story: "В коллекции представлены баночные форматы 0,33 и 0,5 л. Пиво хорошо сочетается с пряными блюдами и подходит для широкой розничной полки.",
    accent: "#b43e31",
  },
  {
    slug: "saigon",
    name: "Saigon",
    country: "Вьетнам",
    type: "Вьетнамское пиво",
    since: "Хошимин",
    image: assetPath("/products/saigon-range.webp"),
    logoText: "BIA SAIGON",
    short: "Популярный вьетнамский бренд с линейкой Special, Lager и Export.",
    intro: "Пиво Saigon производится в Хошимине — крупнейшем мегаполисе Вьетнама.",
    story: "В ассортименте заявлены Saigon Special и Saigon Lager в алюминиевых банках 0,33 л, а также Saigon Export в стеклянных бутылках 0,355 л.",
    accent: "#b45c39",
  },
];

export const products: Product[] = [
  {
    id: "tsingtao-premium-064",
    brand: "tsingtao",
    name: "Tsingtao Premium Lager",
    country: "Китай",
    type: "Лагер",
    volume: "0,64 л",
    abv: "4,7%",
    pack: "12 шт.",
    image: assetPath("/products/imported/tsingtao-premium-064.png"),
    description: "Лёгкий освежающий лагер с чистым солодовым вкусом и деликатной хмелевой горчинкой.",
  },
  {
    id: "tsingtao-premium-033",
    brand: "tsingtao",
    name: "Tsingtao Premium Lager",
    country: "Китай",
    type: "Лагер",
    volume: "0,33 л",
    abv: "4,7%",
    pack: "24 шт.",
    image: assetPath("/products/imported/tsingtao-premium-033.png"),
    description: "Классический формат Tsingtao Premium, подходящий к самой разной кухне.",
  },
  {
    id: "tsingtao-premium-050",
    brand: "tsingtao",
    name: "Tsingtao Premium Lager",
    country: "Китай",
    type: "Лагер",
    volume: "0,5 л",
    abv: "4,7%",
    pack: "24 шт.",
    image: assetPath("/products/imported/tsingtao-premium-050.png"),
    description: "Питкий премиальный лагер в баночном формате 0,5 л.",
  },
  {
    id: "tsingtao-wheat",
    brand: "tsingtao",
    name: "Tsingtao Wheat",
    country: "Китай",
    type: "Пшеничное",
    volume: "0,33 л",
    abv: "4,7%",
    pack: "24 шт.",
    image: assetPath("/products/imported/tsingtao-wheat.png"),
    description: "Мягкое пшеничное пиво с нотами банана, специй и оттенками пшеницы.",
  },
  {
    id: "tsingtao-stout",
    brand: "tsingtao",
    name: "Tsingtao Stout",
    country: "Китай",
    type: "Стаут",
    volume: "0,33 л",
    abv: "6,1%",
    pack: "24 шт.",
    image: assetPath("/products/imported/tsingtao-stout.png"),
    description: "Насыщенное тёмное пиво с оттенками жжёного и карамельного солода.",
  },
  {
    id: "tsingtao-ipa",
    brand: "tsingtao",
    name: "Tsingtao IPA",
    country: "Китай",
    type: "IPA",
    volume: "0,33 л",
    abv: "6,2%",
    pack: "24 шт.",
    image: assetPath("/products/imported/tsingtao-ipa.png"),
    description: "Цитрусовые, цветочные и фруктовые ноты с умеренной горчинкой.",
  },
  {
    id: "tsingtao-zero",
    brand: "tsingtao",
    name: "Tsingtao Zero",
    country: "Китай",
    type: "Безалкогольное",
    volume: "0,33 л",
    abv: "0,0%",
    pack: "24 шт.",
    image: assetPath("/products/imported/tsingtao-zero.png"),
    description: "Безалкогольная версия классического премиального лагера Tsingtao.",
  },
  {
    id: "tsingtao-soda",
    brand: "tsingtao",
    name: "Tsingtao Soda Water",
    country: "Китай",
    type: "Содовая",
    volume: "0,31 л",
    image: assetPath("/products/tsingtao-soda.webp"),
    description: "Содовая вода без сахара, жиров и калорий.",
  },
  {
    id: "harbin-061",
    brand: "harbin",
    name: "Harbin Premium",
    country: "Китай",
    type: "Лагер",
    volume: "0,61 л",
    abv: "5,5%",
    pack: "12 шт.",
    image: assetPath("/products/imported/harbin-061.jpeg"),
    description: "Лагер бледно-золотистого цвета с нотами солода, зерна и трав.",
  },
  {
    id: "harbin-033",
    brand: "harbin",
    name: "Harbin Premium",
    country: "Китай",
    type: "Лагер",
    volume: "0,33 л",
    abv: "5,5%",
    pack: "24 шт.",
    image: assetPath("/products/imported/harbin-033.jpeg"),
    description: "Гладкий, лёгкий и сбалансированный китайский лагер.",
  },
  {
    id: "yanjing-lager-033",
    brand: "yanjing",
    name: "Yanjing Lager",
    country: "Китай",
    type: "Лагер",
    volume: "0,33 л",
    abv: "4,0%",
    pack: "24 шт.",
    image: assetPath("/products/imported/yanjing-lager.png"),
    description: "Мягкий пекинский лагер, подчёркивающий вкус паназиатских блюд.",
  },
  {
    id: "yanjing-lager-061",
    brand: "yanjing",
    name: "Yanjing Lager",
    country: "Китай",
    type: "Лагер",
    volume: "0,61 л",
    abv: "4,0%",
    pack: "12 шт.",
    image: assetPath("/products/imported/yanjing-lager.png"),
    description: "Классический Yanjing Lager в большом бутылочном формате.",
  },
  {
    id: "yanjing-zero-033",
    brand: "yanjing",
    name: "Yanjing Alcohol Free",
    country: "Китай",
    type: "Безалкогольное",
    volume: "0,33 л",
    abv: "до 0,5%",
    pack: "24 шт.",
    composition: "Вода, ячменный и пшеничный солод, дрожжи, хмель.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/yanjing-zero.jpg"),
    description: "Безалкогольная версия пекинского лагера в алюминиевой банке.",
  },
  {
    id: "ha-noi-033",
    brand: "ha-noi",
    name: "Bia Hà Nội",
    country: "Вьетнам",
    type: "Лагер",
    volume: "0,33 л",
    abv: "4,6%",
    pack: "24 шт.",
    image: assetPath("/products/imported/ha-noi.jpg"),
    description: "Светлый лагер с гармоничными солодово-хмелевыми оттенками.",
  },
  {
    id: "ha-noi-049",
    brand: "ha-noi",
    name: "Bia Hà Nội",
    country: "Вьетнам",
    type: "Лагер",
    volume: "0,49 л",
    abv: "4,6%",
    pack: "24 шт.",
    image: assetPath("/products/imported/ha-noi.jpg"),
    description: "Освежающий вьетнамский лагер в увеличенном баночном формате.",
  },
  {
    id: "kaisar-passionfruit",
    brand: "kaisar-king",
    name: "Kaisar King Passion Fruit",
    country: "Китай",
    type: "Пшеничный напиток",
    volume: "1 л",
    abv: "4,5%",
    pack: "12 шт.",
    composition: "Вода, ячменный и пшеничный солод, дрожжи, хмель, концентрированный сок маракуйи.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/kaisar-passionfruit.jpeg"),
    description: "Нефильтрованный пшеничный напиток с ярким вкусом маракуйи.",
  },
  {
    id: "kaisar-strawberry",
    brand: "kaisar-king",
    name: "Kaisar King Strawberry",
    country: "Китай",
    type: "Пшеничный напиток",
    volume: "1 л",
    abv: "4,5%",
    pack: "12 шт.",
    composition: "Вода, ячменный и пшеничный солод, дрожжи, хмель, концентрированный клубничный сок.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/kaisar-strawberry.jpeg"),
    description: "Мягкий пшеничный напиток с выразительным клубничным вкусом.",
  },
  {
    id: "kaisar-peach",
    brand: "kaisar-king",
    name: "Kaisar King Peach",
    country: "Китай",
    type: "Пшеничный напиток",
    volume: "1 л",
    abv: "4,5%",
    pack: "12 шт.",
    composition: "Вода, ячменный и пшеничный солод, персиковый сок.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/kaisar-peach.png"),
    description: "Фруктовый пшеничный напиток с сочным персиковым профилем.",
  },
  {
    id: "tok-rene-cherry",
    brand: "tok-rene",
    name: "TOK RENE Cherry Beer",
    country: "Китай",
    type: "Пшеничный напиток",
    volume: "1 л",
    abv: "4,3%",
    pack: "6 шт.",
    composition: "Вода, ячменный и пшеничный солод, хмель, дрожжи, концентрированные вишнёвый и яблочный соки.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/tok-rene-cherry.jpeg"),
    description: "Нефильтрованный пшеничный напиток с вишнёвым и яблочным соком.",
  },
  {
    id: "tok-rene-pineapple-coconut",
    brand: "tok-rene",
    name: "TOK RENE Pineapple Coconut",
    country: "Китай",
    type: "Пшеничный напиток",
    volume: "1 л",
    abv: "4,3%",
    pack: "6 шт.",
    composition: "Вода, ячменный и пшеничный солод, хмель, дрожжи, концентрированный ананасовый сок, кокосовое молоко.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/tok-rene-pineapple-coconut.jpeg"),
    description: "Тропическое сочетание ананаса и кокоса на пшеничной основе.",
  },
  {
    id: "tok-rene-belgian-wheat",
    brand: "tok-rene",
    name: "TOK RENE Belgian Wheat",
    country: "Китай",
    type: "Пшеничное",
    volume: "5 л",
    abv: "5,0%",
    pack: "4 шт.",
    composition: "Вода, ячменный и пшеничный солод, хмель, дрожжи, концентрированные вишнёвый и яблочный соки.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/tok-rene-belgian-wheat.jpeg"),
    description: "Пшеничное пиво в эффектном пятилитровом формате.",
  },
  {
    id: "tok-rene-craft-white",
    brand: "tok-rene",
    name: "TOK RENE Craft White",
    country: "Китай",
    type: "Светлое нефильтрованное",
    volume: "5 л",
    abv: "5,0%",
    pack: "4 шт.",
    composition: "Вода, ячменный и пшеничный солод, хмель, дрожжи, концентрированный ананасовый сок, кокосовое молоко.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/tok-rene-craft-white.jpeg"),
    description: "Светлое крафтовое пиво в большом формате для компании.",
  },
  {
    id: "big-bisar-050",
    brand: "big-bisar",
    name: "Big Bisar",
    country: "Китай",
    type: "Светлое фильтрованное",
    volume: "0,5 л",
    abv: "3,3%",
    pack: "12 шт.",
    composition: "Вода, ячменный и пшеничный солод, персиковый сок.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/big-bisar.jpeg"),
    description: "Лёгкое пастеризованное пиво плотностью 10° в алюминиевой банке.",
  },
  {
    id: "berlin-priest-stout",
    brand: "berlin-priest",
    name: "Berlin Priest Stout",
    country: "Китай",
    type: "Тёмное фильтрованное",
    volume: "2 л",
    abv: "5,0%",
    pack: "6 шт.",
    composition: "Вода, солод, хмель, дрожжи.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/berlin-priest-stout.jpg"),
    description: "Тёмное пастеризованное пиво в двухлитровой стальной банке.",
  },
  {
    id: "berlin-priest-white",
    brand: "berlin-priest",
    name: "Berlin Priest White Beer",
    country: "Китай",
    type: "Светлое нефильтрованное",
    volume: "2 л",
    abv: "5,0%",
    pack: "6 шт.",
    composition: "Вода, ячменный и пшеничный солод, дрожжи, хмель.",
    shelfLife: "12 месяцев",
    image: assetPath("/products/imported/berlin-priest-white.jpg"),
    description: "Пшеничное белое пиво в большом формате для компании.",
  },
  {
    id: "singha-033",
    brand: "singha",
    name: "Singha Premium Lager",
    country: "Таиланд",
    type: "Лагер",
    volume: "0,33 л",
    abv: "5,0%",
    image: assetPath("/products/singha-033.webp"),
    description: "Ярко-золотой премиальный лагер с дрожжевым оттенком и лёгкой горчинкой.",
  },
  {
    id: "singha-050",
    brand: "singha",
    name: "Singha Premium Lager",
    country: "Таиланд",
    type: "Лагер",
    volume: "0,5 л",
    abv: "5,0%",
    image: assetPath("/products/singha-050.webp"),
    description: "Тайский лагер в баночном формате, особенно подходящий к пряной кухне.",
  },
  {
    id: "singha-061",
    brand: "singha",
    name: "Singha Premium Lager",
    country: "Таиланд",
    type: "Лагер",
    volume: "0,61 л",
    abv: "5,0%",
    image: assetPath("/products/singha-061.webp"),
    description: "Фирменный золотой лагер Singha в большом бутылочном формате.",
  },
  {
    id: "leo-033",
    brand: "leo",
    name: "Leo Premium",
    country: "Таиланд",
    type: "Лагер",
    volume: "0,33 л",
    image: assetPath("/products/leo-033.webp"),
    description: "Сбалансированный тайский лагер с ровным, чистым характером.",
  },
  {
    id: "leo-050",
    brand: "leo",
    name: "Leo Premium",
    country: "Таиланд",
    type: "Лагер",
    volume: "0,5 л",
    image: assetPath("/products/leo-050.webp"),
    description: "Популярный в Таиланде светлый лагер в формате 0,5 л.",
  },
  {
    id: "saigon-special",
    brand: "saigon",
    name: "Saigon Special",
    country: "Вьетнам",
    type: "Лагер",
    volume: "0,33 л",
    image: assetPath("/products/saigon-range.webp"),
    description: "Одна из ключевых позиций вьетнамского портфеля Saigon.",
  },
  {
    id: "saigon-lager",
    brand: "saigon",
    name: "Saigon Lager",
    country: "Вьетнам",
    type: "Лагер",
    volume: "0,33 л",
    image: assetPath("/products/saigon-range.webp"),
    description: "Светлый вьетнамский лагер в алюминиевой банке.",
  },
  {
    id: "saigon-export",
    brand: "saigon",
    name: "Saigon Export",
    country: "Вьетнам",
    type: "Лагер",
    volume: "0,355 л",
    image: assetPath("/products/saigon-range.webp"),
    description: "Экспортная линейка Saigon в стеклянной бутылке.",
  },
];
